version: "3.4"
services:
  nginx:
    image: nginx:1.23.0-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - client
      - server

  client:
    build:
      context: ./client
    depends_on:
      - server

  server:
    build:
      context: ./server
    depends_on:
      - postgres
      - redis
    environment:
      - PORT=4200
      - SESSION_SECRET
      - ORIGIN
      - REDIS_PASSWORD
      - DB_USERNAME
      - DB_PASSWORD

  postgres:
    image: postgres:14.4-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=postgres

  redis:
    image: redis:7.0.2-alpine
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
